name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/docker.yml"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials with OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::591127499740:role/github-actions-ecr-role
          aws-region: eu-west-3

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region eu-west-3 | docker login --username AWS --password-stdin 591127499740.dkr.ecr.eu-west-3.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t my-app ./app

      - name: Tag image
        run: |
          docker tag my-app:latest 591127499740.dkr.ecr.eu-west-3.amazonaws.com/my-app-repo:latest

      - name: Push to ECR
        run: |
          docker push 591127499740.dkr.ecr.eu-west-3.amazonaws.com/my-app-repo:latest

      - name: Force new ECS deployment
        run: |
          aws ecs update-service \
            --cluster resilient-aws-infra-ecs-cluster \
            --service resilient-aws-infra-ecs-service \
            --force-new-deployment \
            --region eu-west-3
